QUESTION_BANK = [
    {'question': 'The capital of France is Paris.', 'answer': 'True'},
    {'question': 'The Earth is flat.', 'answer': 'False'},
    {'question': 'There are 365 days in a year.', 'answer': 'True'},
    {'question': 'A leap year has 366 days.', 'answer': 'True'},
    {'question': 'The chemical symbol for water is H2O.', 'answer': 'True'},
    {'question': 'Humans have four hearts.', 'answer': 'False'},
    {'question': 'The Great Wall of China is visible from space.', 'answer': 'False'},
    {'question': 'Lightning never strikes the same place twice.', 'answer': 'False'},
    {'question': 'The Sun is a star.', 'answer': 'True'},
    {'question': 'Venus is the closest planet to the Sun.', 'answer': 'False'},
    {'question': 'Humans breathe oxygen.', 'answer': 'True'},
    {'question': 'An octopus has three hearts.', 'answer': 'True'},
    {'question': 'Mount Everest is the tallest mountain on Earth.', 'answer': 'True'},
    {'question': 'Penguins can fly.', 'answer': 'False'},
    {'question': 'Bananas grow on trees.', 'answer': 'False'},
    {'question': 'Sharks are mammals.', 'answer': 'False'},
    {'question': 'The Amazon River is the longest river in the world.', 'answer': 'False'},
    {'question': 'Sound travels faster than light.', 'answer': 'False'},
    {'question': 'The human body has 206 bones.', 'answer': 'True'},
    {'question': 'Jupiter is the largest planet in our solar system.', 'answer': 'True'},
    {'question': 'Bats are blind.', 'answer': 'False'},
    {'question': 'An ostrich\'s eye is bigger than its brain.', 'answer': 'True'},
    {'question': 'Gold is heavier than silver.', 'answer': 'True'},
    {'question': 'Water boils at 100 degrees Celsius.', 'answer': 'True'},
    {'question': 'There are 12 months in a year.', 'answer': 'True'},
    {'question': 'The capital of Japan is Beijing.', 'answer': 'False'},
    {'question': 'Diamonds are made of carbon.', 'answer': 'True'},
    {'question': 'The Pacific Ocean is the largest ocean on Earth.', 'answer': 'True'},
    {'question': 'Giraffes have the same number of neck vertebrae as humans.', 'answer': 'True'},
    {'question': 'There are 8 planets in our solar system.', 'answer': 'True'},
    {'question': 'Humans have two lungs.', 'answer': 'True'},
    {'question': 'The speed of light is faster than the speed of sound.', 'answer': 'True'},
    {'question': 'A hexagon has five sides.', 'answer': 'False'},
    {'question': 'A heptagon has seven sides.', 'answer': 'True'},
    {'question': 'The Earth revolves around the Sun.', 'answer': 'True'},
    {'question': 'Fish can drown.', 'answer': 'True'},
    {'question': 'The Mona Lisa was painted by Vincent van Gogh.', 'answer': 'False'},
    {'question': 'The square root of 9 is 3.', 'answer': 'True'},
    {'question': 'Dogs are herbivores.', 'answer': 'False'},
    {'question': 'An eagle is a bird of prey.', 'answer': 'True'},
    {'question': 'Honey never spoils.', 'answer': 'True'},
    {'question': 'The Eiffel Tower is in London.', 'answer': 'False'},
    {'question': 'There are 50 states in the United States.', 'answer': 'True'},
    {'question': 'Spiders are insects.', 'answer': 'False'},
    {'question': 'The chemical symbol for gold is Au.', 'answer': 'True'},
    {'question': 'The largest desert in the world is the Sahara.', 'answer': 'False'},
    {'question': 'The capital of Australia is Sydney.', 'answer': 'False'},
    {'question': 'The human heart has four chambers.', 'answer': 'True'},
    {'question': 'Polar bears live in the Antarctic.', 'answer': 'False'},
    {'question': 'A triangle has three sides.', 'answer': 'True'},
    {'question': 'The capital of Italy is Rome.', 'answer': 'True'},
    {'question': 'Lightning is hotter than the surface of the sun.', 'answer': 'True'},
    {'question': 'A caterpillar turns into a butterfly.', 'answer': 'True'},
    {'question': 'The atomic number of hydrogen is 1.', 'answer': 'True'},
    {'question': 'Sharks have bones.', 'answer': 'False'},
    {'question': 'The piano has 88 keys.', 'answer': 'True'},
    {'question': 'Venus is the hottest planet in our solar system.', 'answer': 'True'},
    {'question': 'The human eye can distinguish 10 million different colors.', 'answer': 'True'},
    {'question': 'The fastest land animal is the cheetah.', 'answer': 'True'},
    {'question': 'Albert Einstein developed the theory of general relativity.', 'answer': 'True'},
    {'question': 'Mercury is the heaviest liquid.', 'answer': 'False'},
    {'question': 'The capital of Canada is Ottawa.', 'answer': 'True'},
    {'question': 'A group of lions is called a pride.', 'answer': 'True'},
    {'question': 'The longest river in Africa is the Nile.', 'answer': 'True'},
    {'question': 'Sharks lay eggs.', 'answer': 'True'},
    {'question': 'The chemical symbol for iron is Fe.', 'answer': 'True'},
    {'question': 'There are 5 continents in the world.', 'answer': 'False'},
    {'question': 'Birds are reptiles.', 'answer': 'True'},
    {'question': 'The capital of Egypt is Cairo.', 'answer': 'True'},
    {'question': 'A person has 32 permanent teeth.', 'answer': 'True'},
    {'question': 'An octopus has eight legs.', 'answer': 'False'},
    {'question': 'An apple a day keeps the doctor away.', 'answer': 'False'},
    {'question': 'The Atlantic Ocean is larger than the Indian Ocean.', 'answer': 'True'},
    {'question': 'There are 7 colors in a rainbow.', 'answer': 'True'},
    {'question': 'The sun rises in the west.', 'answer': 'False'},
    {'question': 'A year on Mars is longer than a year on Earth.', 'answer': 'True'},
    {'question': 'The smallest bone in the human body is in the ear.', 'answer': 'True'},
    {'question': 'The Eiffel Tower was a gift from the United States to France.', 'answer': 'False'},
    {'question': 'Butterflies taste with their feet.', 'answer': 'True'},
    {'question': 'The largest planet in the solar system is Saturn.', 'answer': 'False'},
    {'question': 'An adult human has 4 liters of blood.', 'answer': 'False'},
    {'question': 'Cows can walk upstairs but not downstairs.', 'answer': 'True'},
    {'question': 'Chocolate is toxic to dogs.', 'answer': 'True'},
    {'question': 'Humans can breathe underwater without any equipment.', 'answer': 'False'},
    {'question': 'A square has four equal sides.', 'answer': 'True'},
    {'question': 'Bamboo is the fastest-growing plant.', 'answer': 'True'},
    {'question': 'Light travels in a straight line.', 'answer': 'True'},
    {'question': 'Humans share 50% of their DNA with bananas.', 'answer': 'True'},
    {'question': 'Snakes have eyelids.', 'answer': 'False'},
    {'question': 'A blue whale is the largest animal on Earth.', 'answer': 'True'},
    {'question': 'The Statue of Liberty is in Washington, D.C.', 'answer': 'False'},
    {'question': 'The capital of Germany is Berlin.', 'answer': 'True'},
    {'question': 'The currency of Japan is the Yen.', 'answer': 'True'},
    {'question': 'A bee dies after it stings.', 'answer': 'True'},
    {'question': 'Humans have more than 5 senses.', 'answer': 'True'},
    {'question': 'The capital of Spain is Madrid.', 'answer': 'True'},
    {'question': 'A hexagon has six sides.', 'answer': 'True'}
]
